-- Create a table for public profiles
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role text default 'controller' check (role in ('admin', 'controller')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for 'registros' (Sales/Contacts)
create table if not exists registros (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users default auth.uid(),
  
  -- Fields based on "Sales Contact System"
  data_contato date not null default current_date,
  cliente_nome text not null,
  tipo_contato text, -- e.g., Email, Phone, WhatsApp
  produto text,
  valor numeric,
  status text default 'Pendente' check (status in ('Pendente', 'Aprovado', 'Rejeitado', 'Em Andamento')),
  observacoes text
);

alter table registros enable row level security;

create policy "Registros are viewable by everyone." on registros
  for select using (true);

create policy "Controllers can insert registros." on registros
  for insert with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and (role = 'controller' or role = 'admin')
    )
  );

create policy "Controllers can update own registros." on registros
  for update using (
     auth.uid() = user_id
  );

create policy "Admins can do everything on registros." on registros
  for all using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Trigger to create profile on signup
-- Drop trigger if exists to allow re-running
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'controller');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
